steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/mymomentumapp/momentum-client', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/mymomentumapp/momentum-client']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'momentum-client',
      '--image', 'gcr.io/mymomentumapp/momentum-client',
      '--platform', 'managed',
      '--region', 'us-central1',
