steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'client'
    args: [
      'build',
      '-t', 'gcr.io/mymomentumapp/momentum-client',
      '--build-arg', 'REACT_APP_API_URL=${_REACT_APP_API_URL}',
      '--build-arg', 'REACT_APP_FIREBASE_API_KEY=${_REACT_APP_FIREBASE_API_KEY}',
      '--build-arg', 'REACT_APP_FIREBASE_AUTH_DOMAIN=${_REACT_APP_FIREBASE_AUTH_DOMAIN}',
      '--build-arg', 'REACT_APP_FIREBASE_PROJECT_ID=${_REACT_APP_FIREBASE_PROJECT_ID}',
      '--build-arg', 'REACT_APP_FIREBASE_STORAGE_BUCKET=${_REACT_APP_FIREBASE_STORAGE_BUCKET}',
      '--build-arg', 'REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${_REACT_APP_FIREBASE_MESSAGING_SENDER_ID}',
      '--build-arg', 'REACT_APP_FIREBASE_APP_ID=${_REACT_APP_FIREBASE_APP_ID}',
      '--build-arg', 'REACT_APP_FIREBASE_MEASUREMENT_ID=${_REACT_APP_FIREBASE_MEASUREMENT_ID}',
      '.'
    ]
    secretEnv: [
      '_REACT_APP_API_URL',
      '_REACT_APP_FIREBASE_API_KEY',
      '_REACT_APP_FIREBASE_AUTH_DOMAIN',
      '_REACT_APP_FIREBASE_PROJECT_ID',
      '_REACT_APP_FIREBASE_STORAGE_BUCKET',
      '_REACT_APP_FIREBASE_MESSAGING_SENDER_ID',
      '_REACT_APP_FIREBASE_APP_ID',
      '_REACT_APP_FIREBASE_MEASUREMENT_ID'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/mymomentumapp/momentum-client']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'momentum-client'
      - '--image'
      - 'gcr.io/mymomentumapp/momentum-client'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'

images:
  - 'gcr.io/mymomentumapp/momentum-client'

options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/_REACT_APP_API_URL/versions/latest
      env: '_REACT_APP_API_URL'
    - versionName: projects/$PROJECT_ID/secrets/_REACT_APP_FIREBASE_API_KEY/versions/latest
      env: '_REACT_APP_FIREBASE_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/_REACT_APP_FIREBASE_AUTH_DOMAIN/versions/latest
      env: '_REACT_APP_FIREBASE_AUTH_DOMAIN'
    - versionName: projects/$PROJECT_ID/secrets/_REACT_APP_FIREBASE_PROJECT_ID/versions/latest
      env: '_REACT_APP_FIREBASE_PROJECT_ID'
    - versionName: projects/$PROJECT_ID/secrets/_REACT_APP_FIREBASE_STORAGE_BUCKET/versions/latest
      env: '_REACT_APP_FIREBASE_STORAGE_BUCKET'
    - versionName: projects/$PROJECT_ID/secrets/_REACT_APP_FIREBASE_MESSAGING_SENDER_ID/versions/latest
      env: '_REACT_APP_FIREBASE_MESSAGING_SENDER_ID'
    - versionName: projects/$PROJECT_ID/secrets/_REACT_APP_FIREBASE_APP_ID/versions/latest
      env: '_REACT_APP_FIREBASE_APP_ID'
    - versionName: projects/$PROJECT_ID/secrets/_REACT_APP_FIREBASE_MEASUREMENT_ID/versions/latest
      env: '_REACT_APP_FIREBASE_MEASUREMENT_ID'
