steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'client'
    args: ['build', '-t', 'gcr.io/mymomentumapp/momentum-client', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/mymomentumapp/momentum-client']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'momentum-client'
      - '--image'
      - 'gcr.io/mymomentumapp/momentum-client'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--min-instances'
      - '1'
      - '--set-secrets'
      - 'REACT_APP_API_URL=REACT_APP_API_URL:latest'
      - '--set-secrets'
      - 'REACT_APP_FIREBASE_API_KEY=REACT_APP_FIREBASE_API_KEY:latest'
      - '--set-secrets'
      - 'REACT_APP_FIREBASE_AUTH_DOMAIN=REACT_APP_FIREBASE_AUTH_DOMAIN:latest'
      - '--set-secrets'
      - 'REACT_APP_FIREBASE_PROJECT_ID=REACT_APP_FIREBASE_PROJECT_ID:latest'
      - '--set-secrets'
      - 'REACT_APP_FIREBASE_STORAGE_BUCKET=REACT_APP_FIREBASE_STORAGE_BUCKET:latest'
      - '--set-secrets'
      - 'REACT_APP_FIREBASE_MESSAGING_SENDER_ID=REACT_APP_FIREBASE_MESSAGING_SENDER_ID:latest'
      - '--set-secrets'
      - 'REACT_APP_FIREBASE_APP_ID=REACT_APP_FIREBASE_APP_ID:latest'
      - '--set-secrets'
      - 'REACT_APP_FIREBASE_MEASUREMENT_ID=REACT_APP_FIREBASE_MEASUREMENT_ID:latest'

images:
  - 'gcr.io/mymomentumapp/momentum-client'

options:
  logging: CLOUD_LOGGING_ONLY
