steps:
  # Build the Docker image with secrets
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'client'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/mymomentumapp/momentum-client'
      - '--build-arg'
      - 'REACT_APP_API_URL=${REACT_APP_API_URL}'
      - '--build-arg'
      - 'REACT_APP_FIREBASE_API_KEY=${REACT_APP_FIREBASE_API_KEY}'
      - '--build-arg'
      - 'REACT_APP_FIREBASE_AUTH_DOMAIN=${REACT_APP_FIREBASE_AUTH_DOMAIN}'
      - '--build-arg'
      - 'REACT_APP_FIREBASE_PROJECT_ID=${REACT_APP_FIREBASE_PROJECT_ID}'
      - '--build-arg'
      - 'REACT_APP_FIREBASE_STORAGE_BUCKET=${REACT_APP_FIREBASE_STORAGE_BUCKET}'
      - '--build-arg'
      - 'REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${REACT_APP_FIREBASE_MESSAGING_SENDER_ID}'
      - '--build-arg'
      - 'REACT_APP_FIREBASE_APP_ID=${REACT_APP_FIREBASE_APP_ID}'
      - '--build-arg'
      - 'REACT_APP_FIREBASE_MEASUREMENT_ID=${REACT_APP_FIREBASE_MEASUREMENT_ID}'
      - '.'
    secretEnv:
      - 'REACT_APP_API_URL'
      - 'REACT_APP_FIREBASE_API_KEY'
      - 'REACT_APP_FIREBASE_AUTH_DOMAIN'
      - 'REACT_APP_FIREBASE_PROJECT_ID'
      - 'REACT_APP_FIREBASE_STORAGE_BUCKET'
      - 'REACT_APP_FIREBASE_MESSAGING_SENDER_ID'
      - 'REACT_APP_FIREBASE_APP_ID'
      - 'REACT_APP_FIREBASE_MEASUREMENT_ID'

  # Add a debug step to verify environment variables
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Checking build variables:"
        echo "API URL exists: ${REACT_APP_API_URL:+yes}"
        echo "Firebase API Key exists: ${REACT_APP_FIREBASE_API_KEY:+yes}"
        echo "Project ID exists: ${REACT_APP_FIREBASE_PROJECT_ID:+yes}"

  # Push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/mymomentumapp/momentum-client']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'momentum-client'
      - '--image'
      - 'gcr.io/mymomentumapp/momentum-client'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--min-instances'
      - '1'

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/REACT_APP_API_URL/versions/latest
      env: 'REACT_APP_API_URL'
    - versionName: projects/$PROJECT_ID/secrets/REACT_APP_FIREBASE_API_KEY/versions/latest
      env: 'REACT_APP_FIREBASE_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/REACT_APP_FIREBASE_AUTH_DOMAIN/versions/latest
      env: 'REACT_APP_FIREBASE_AUTH_DOMAIN'
    - versionName: projects/$PROJECT_ID/secrets/REACT_APP_FIREBASE_PROJECT_ID/versions/latest
      env: 'REACT_APP_FIREBASE_PROJECT_ID'
    - versionName: projects/$PROJECT_ID/secrets/REACT_APP_FIREBASE_STORAGE_BUCKET/versions/latest
      env: 'REACT_APP_FIREBASE_STORAGE_BUCKET'
    - versionName: projects/$PROJECT_ID/secrets/REACT_APP_FIREBASE_MESSAGING_SENDER_ID/versions/latest
      env: 'REACT_APP_FIREBASE_MESSAGING_SENDER_ID'
    - versionName: projects/$PROJECT_ID/secrets/REACT_APP_FIREBASE_APP_ID/versions/latest
      env: 'REACT_APP_FIREBASE_APP_ID'
    - versionName: projects/$PROJECT_ID/secrets/REACT_APP_FIREBASE_MEASUREMENT_ID/versions/latest
      env: 'REACT_APP_FIREBASE_MEASUREMENT_ID'

images:
  - 'gcr.io/mymomentumapp/momentum-client'

options:
  logging: CLOUD_LOGGING_ONLY
