steps:
  # Debug step: Verify secret access
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Testing secret access..."
        REACT_APP_API_URL=$$(gcloud secrets versions access latest --secret="react-app-api-url" --project="mymomentumapp")
        REACT_APP_FIREBASE_API_KEY=$$(gcloud secrets versions access latest --secret="react-app-firebase-api-key" --project="mymomentumapp")
        echo "API URL: $$REACT_APP_API_URL"
        echo "Firebase API Key: $$REACT_APP_FIREBASE_API_KEY"
        
        # Create .env file
        echo "Creating .env file..."
        cat > client/.env << EOL
        REACT_APP_API_URL="$$REACT_APP_API_URL"
        REACT_APP_FIREBASE_API_KEY="$$REACT_APP_FIREBASE_API_KEY"
        REACT_APP_FIREBASE_AUTH_DOMAIN="$$(gcloud secrets versions access latest --secret="react-app-firebase-auth-domain" --project="mymomentumapp")"
        REACT_APP_FIREBASE_PROJECT_ID="$$(gcloud secrets versions access latest --secret="react-app-firebase-project-id" --project="mymomentumapp")"
        REACT_APP_FIREBASE_STORAGE_BUCKET="$$(gcloud secrets versions access latest --secret="react-app-firebase-storage-bucket" --project="mymomentumapp")"
        REACT_APP_FIREBASE_MESSAGING_SENDER_ID="$$(gcloud secrets versions access latest --secret="react-app-firebase-messaging-sender-id" --project="mymomentumapp")"
        REACT_APP_FIREBASE_APP_ID="$$(gcloud secrets versions access latest --secret="react-app-firebase-app-id" --project="mymomentumapp")"
        REACT_APP_FIREBASE_MEASUREMENT_ID="$$(gcloud secrets versions access latest --secret="react-app-firebase-measurement-id" --project="mymomentumapp")"
        EOL
        
        echo "Contents of .env file (masked):"
        cat client/.env | sed 's/=.*$/=****/'

  # Build step
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'client'
    args: [
      'build',
      '-t', 'gcr.io/mymomentumapp/momentum-client',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/mymomentumapp/momentum-client']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'momentum-client'
      - '--image'
      - 'gcr.io/mymomentumapp/momentum-client'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'

images:
  - 'gcr.io/mymomentumapp/momentum-client'

options:
  logging: CLOUD_LOGGING_ONLY
