steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'client'
    args: [
      'build',
      '-t', 'gcr.io/mymomentumapp/momentum-client',
      '--build-arg', 'REACT_APP_API_URL=${_REACT_APP_API_URL}',
      '--build-arg', 'REACT_APP_FIREBASE_API_KEY=${_REACT_APP_FIREBASE_API_KEY}',
      '--build-arg', 'REACT_APP_FIREBASE_AUTH_DOMAIN=${_REACT_APP_FIREBASE_AUTH_DOMAIN}',
      '--build-arg', 'REACT_APP_FIREBASE_PROJECT_ID=${_REACT_APP_FIREBASE_PROJECT_ID}',
      '--build-arg', 'REACT_APP_FIREBASE_STORAGE_BUCKET=${_REACT_APP_FIREBASE_STORAGE_BUCKET}',
      '--build-arg', 'REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${_REACT_APP_FIREBASE_MESSAGING_SENDER_ID}',
      '--build-arg', 'REACT_APP_FIREBASE_APP_ID=${_REACT_APP_FIREBASE_APP_ID}',
      '--build-arg', 'REACT_APP_FIREBASE_MEASUREMENT_ID=${_REACT_APP_FIREBASE_MEASUREMENT_ID}',
      '.'
    ]
    secretEnv: [
      'REACT_APP_API_URL',
      'REACT_APP_FIREBASE_API_KEY',
      'REACT_APP_FIREBASE_AUTH_DOMAIN',
      'REACT_APP_FIREBASE_PROJECT_ID',
      'REACT_APP_FIREBASE_STORAGE_BUCKET',
      'REACT_APP_FIREBASE_MESSAGING_SENDER_ID',
      'REACT_APP_FIREBASE_APP_ID',
      'REACT_APP_FIREBASE_MEASUREMENT_ID'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/mymomentumapp/momentum-client']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'momentum-client'
      - '--image'
      - 'gcr.io/mymomentumapp/momentum-client'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--min-instances'
      - '1'
      - '--set-secrets'
      - 'REACT_APP_API_URL=react-app-api-url:latest,REACT_APP_FIREBASE_API_KEY=react-app-firebase-api-key:latest,REACT_APP_FIREBASE_AUTH_DOMAIN=react-app-firebase-auth-domain:latest,REACT_APP_FIREBASE_PROJECT_ID=react-app-firebase-project-id:latest,REACT_APP_FIREBASE_STORAGE_BUCKET=react-app-firebase-storage-bucket:latest,REACT_APP_FIREBASE_MESSAGING_SENDER_ID=react-app-firebase-messaging-sender-id:latest,REACT_APP_FIREBASE_APP_ID=react-app-firebase-app-id:latest,REACT_APP_FIREBASE_MEASUREMENT_ID=react-app-firebase-measurement-id:latest'

images:
  - 'gcr.io/mymomentumapp/momentum-client'

options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/mymomentumapp/secrets/react-app-api-url/versions/latest
      env: 'REACT_APP_API_URL'
    - versionName: projects/mymomentumapp/secrets/react-app-firebase-api-key/versions/latest
      env: 'REACT_APP_FIREBASE_API_KEY'
    - versionName: projects/mymomentumapp/secrets/react-app-firebase-auth-domain/versions/latest
      env: 'REACT_APP_FIREBASE_AUTH_DOMAIN'
    - versionName: projects/mymomentumapp/secrets/react-app-firebase-project-id/versions/latest
      env: 'REACT_APP_FIREBASE_PROJECT_ID'
    - versionName: projects/mymomentumapp/secrets/react-app-firebase-storage-bucket/versions/latest
      env: 'REACT_APP_FIREBASE_STORAGE_BUCKET'
    - versionName: projects/mymomentumapp/secrets/react-app-firebase-messaging-sender-id/versions/latest
      env: 'REACT_APP_FIREBASE_MESSAGING_SENDER_ID'
    - versionName: projects/mymomentumapp/secrets/react-app-firebase-app-id/versions/latest
      env: 'REACT_APP_FIREBASE_APP_ID'
    - versionName: projects/mymomentumapp/secrets/react-app-firebase-measurement-id/versions/latest
      env: 'REACT_APP_FIREBASE_MEASUREMENT_ID'
