steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'server'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/mymomentumapp/momentum-server'
      - '--build-arg'
      - 'FIREBASE_TYPE="${_FIREBASE_TYPE}"'
      - '--build-arg'
      - 'FIREBASE_PROJECT_ID="${_FIREBASE_PROJECT_ID}"'
      - '--build-arg'
      - 'FIREBASE_PRIVATE_KEY_ID="${_FIREBASE_PRIVATE_KEY_ID}"'
      - '--build-arg'
      - 'FIREBASE_PRIVATE_KEY="${_FIREBASE_PRIVATE_KEY}"'
      - '--build-arg'
      - 'FIREBASE_CLIENT_EMAIL="${_FIREBASE_CLIENT_EMAIL}"'
      - '--build-arg'
      - 'FIREBASE_CLIENT_ID="${_FIREBASE_CLIENT_ID}"'
      - '--build-arg'
      - 'FIREBASE_AUTH_URI="${_FIREBASE_AUTH_URI}"'
      - '--build-arg'
      - 'FIREBASE_TOKEN_URI="${_FIREBASE_TOKEN_URI}"'
      - '--build-arg'
      - 'FIREBASE_AUTH_PROVIDER_X509_CERT_URL="${_FIREBASE_AUTH_PROVIDER_X509_CERT_URL}"'
      - '--build-arg'
      - 'FIREBASE_CLIENT_X509_CERT_URL="${_FIREBASE_CLIENT_X509_CERT_URL}"'
      - '--build-arg'
      - 'FIREBASE_UNIVERSE_DOMAIN="${_FIREBASE_UNIVERSE_DOMAIN}"'
      - '.'
    secretEnv:
      - '_FIREBASE_TYPE'
      - '_FIREBASE_PROJECT_ID'
      - '_FIREBASE_PRIVATE_KEY_ID'
      - '_FIREBASE_PRIVATE_KEY'
      - '_FIREBASE_CLIENT_EMAIL'
      - '_FIREBASE_CLIENT_ID'
      - '_FIREBASE_AUTH_URI'
      - '_FIREBASE_TOKEN_URI'
      - '_FIREBASE_AUTH_PROVIDER_X509_CERT_URL'
      - '_FIREBASE_CLIENT_X509_CERT_URL'
      - '_FIREBASE_UNIVERSE_DOMAIN'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/mymomentumapp/momentum-server']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'momentum-server'
      - '--image'
      - 'gcr.io/mymomentumapp/momentum-server'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--min-instances'
      - '1'
      - '--set-secrets'
      - 'FIREBASE_TYPE=FIREBASE_TYPE:latest'
      - '--set-secrets'
      - 'FIREBASE_PROJECT_ID=FIREBASE_PROJECT_ID:latest'
      - '--set-secrets'
      - 'FIREBASE_PRIVATE_KEY_ID=FIREBASE_PRIVATE_KEY_ID:latest'
      - '--set-secrets'
      - 'FIREBASE_PRIVATE_KEY=FIREBASE_PRIVATE_KEY:latest'
      - '--set-secrets'
      - 'FIREBASE_CLIENT_EMAIL=FIREBASE_CLIENT_EMAIL:latest'
      - '--set-secrets'
      - 'FIREBASE_CLIENT_ID=FIREBASE_CLIENT_ID:latest'
      - '--set-secrets'
      - 'FIREBASE_AUTH_URI=FIREBASE_AUTH_URI:latest'
      - '--set-secrets'
      - 'FIREBASE_TOKEN_URI=FIREBASE_TOKEN_URI:latest'
      - '--set-secrets'
      - 'FIREBASE_AUTH_PROVIDER_X509_CERT_URL=FIREBASE_AUTH_PROVIDER_X509_CERT_URL:latest'
      - '--set-secrets'
      - 'FIREBASE_CLIENT_X509_CERT_URL=FIREBASE_CLIENT_X509_CERT_URL:latest'
      - '--set-secrets'
      - 'FIREBASE_UNIVERSE_DOMAIN=FIREBASE_UNIVERSE_DOMAIN:latest'

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_TYPE/versions/latest
      env: '_FIREBASE_TYPE'
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_PROJECT_ID/versions/latest
      env: '_FIREBASE_PROJECT_ID'
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_PRIVATE_KEY_ID/versions/latest
      env: '_FIREBASE_PRIVATE_KEY_ID'
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_PRIVATE_KEY/versions/latest
      env: '_FIREBASE_PRIVATE_KEY'
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_CLIENT_EMAIL/versions/latest
      env: '_FIREBASE_CLIENT_EMAIL'
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_CLIENT_ID/versions/latest
      env: '_FIREBASE_CLIENT_ID'
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_AUTH_URI/versions/latest
      env: '_FIREBASE_AUTH_URI'
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_TOKEN_URI/versions/latest
      env: '_FIREBASE_TOKEN_URI'
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_AUTH_PROVIDER_X509_CERT_URL/versions/latest
      env: '_FIREBASE_AUTH_PROVIDER_X509_CERT_URL'
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_CLIENT_X509_CERT_URL/versions/latest
      env: '_FIREBASE_CLIENT_X509_CERT_URL'
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_UNIVERSE_DOMAIN/versions/latest
      env: '_FIREBASE_UNIVERSE_DOMAIN'

images:
  - 'gcr.io/mymomentumapp/momentum-server'

options:
  logging: CLOUD_LOGGING_ONLY