steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'server'
    args: ['build', '-t', 'gcr.io/mymomentumapp/momentum-server', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/mymomentumapp/momentum-server']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'momentum-server'
      - '--image'
      - 'gcr.io/mymomentumapp/momentum-server'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--min-instances'
      - '1'
      - '--set-secrets'
      - 'PORT=PORT:latest'
      - '--set-secrets'
      - 'FIREBASE_TYPE=FIREBASE_TYPE:latest'
      - '--set-secrets'
      - 'FIREBASE_PROJECT_ID=FIREBASE_PROJECT_ID:latest'
      - '--set-secrets'
      - 'FIREBASE_PRIVATE_KEY_ID=FIREBASE_PRIVATE_KEY_ID:latest'
      - '--set-secrets'
      - 'FIREBASE_PRIVATE_KEY=FIREBASE_PRIVATE_KEY:latest'
      - '--set-secrets'
      - 'FIREBASE_CLIENT_EMAIL=FIREBASE_CLIENT_EMAIL:latest'
      - '--set-secrets'
      - 'FIREBASE_CLIENT_ID=FIREBASE_CLIENT_ID:latest'
      - '--set-secrets'
      - 'FIREBASE_AUTH_URI=FIREBASE_AUTH_URI:latest'
      - '--set-secrets'
      - 'FIREBASE_TOKEN_URI=FIREBASE_TOKEN_URI:latest'
      - '--set-secrets'
      - 'FIREBASE_AUTH_PROVIDER_X509_CERT_URL=FIREBASE_AUTH_PROVIDER_X509_CERT_URL:latest'
      - '--set-secrets'
      - 'FIREBASE_CLIENT_X509_CERT_URL=FIREBASE_CLIENT_X509_CERT_URL:latest'
      - '--set-secrets'
      - 'FIREBASE_UNIVERSE_DOMAIN=FIREBASE_UNIVERSE_DOMAIN:latest'

images:
  - 'gcr.io/mymomentumapp/momentum-server'

options:
  logging: CLOUD_LOGGING_ONLY