steps:
  # Create .env file with secrets
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Creating .env file with secrets..."
        (
          echo "FIREBASE_TYPE=$$(gcloud secrets versions access latest --secret="firebase-type" --project="mymomentumapp")"
          echo "FIREBASE_PROJECT_ID=$$(gcloud secrets versions access latest --secret="firebase-project-id" --project="mymomentumapp")"
          echo "FIREBASE_PRIVATE_KEY_ID=$$(gcloud secrets versions access latest --secret="firebase-private-key-id" --project="mymomentumapp")"
          echo "FIREBASE_PRIVATE_KEY=$$(gcloud secrets versions access latest --secret="firebase-private-key" --project="mymomentumapp")"
          echo "FIREBASE_CLIENT_EMAIL=$$(gcloud secrets versions access latest --secret="firebase-client-email" --project="mymomentumapp")"
          echo "FIREBASE_CLIENT_ID=$$(gcloud secrets versions access latest --secret="firebase-client-id" --project="mymomentumapp")"
          echo "FIREBASE_AUTH_URI=$$(gcloud secrets versions access latest --secret="firebase-auth-uri" --project="mymomentumapp")"
          echo "FIREBASE_TOKEN_URI=$$(gcloud secrets versions access latest --secret="firebase-token-uri" --project="mymomentumapp")"
          echo "FIREBASE_AUTH_PROVIDER_X509_CERT_URL=$$(gcloud secrets versions access latest --secret="firebase-auth-provider-x509-cert-url" --project="mymomentumapp")"
          echo "FIREBASE_CLIENT_X509_CERT_URL=$$(gcloud secrets versions access latest --secret="firebase-client-x509-cert-url" --project="mymomentumapp")"
          echo "JWT_SECRET=$$(gcloud secrets versions access latest --secret="jwt-secret" --project="mymomentumapp")"
        ) > server/.env
        
        echo "Contents of .env file (masked):"
        cat server/.env | sed 's/=.*$/=****/'
        
        echo "Verifying .env file location and permissions:"
        ls -la server/.env

  # Build step
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'server'
    args: [
      'build',
      '-t', 'gcr.io/mymomentumapp/momentum-server',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/mymomentumapp/momentum-server']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'momentum-server'
      - '--image'
      - 'gcr.io/mymomentumapp/momentum-server'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--min-instances'
      - '1'

images:
  - 'gcr.io/mymomentumapp/momentum-server'

options:
  logging: CLOUD_LOGGING_ONLY