# fly.toml app configuration file generated for momentum-tracker on 2024-10-27T06:08:51Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'momentum-tracker'
primary_region = 'sea'

[build]

[http_service]
  internal_port = 5002
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
